name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ gh-pages ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      - name: Checkout repository using git
        uses: actions/checkout@v5
      - name: Run tests
        run: cd test && ./test.sh

  build:
    needs: test
    if: github.repository == 'w3c-cg/musicxml'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v5
      - name: Install, build, and upload site
        uses: withastro/action@v5
        with:
          path: ./docs
        env:
          ORIGIN: ${{ vars.ORIGIN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
