name: Run tests only

on:
  push:
    branches: ['*', '!gh-pages']

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libxml2-utils xsltproc python3-pip jq && pip install saxonche
      - name: Checkout repository using git
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Run tests
        run: cd tests && ./test.sh
